function query(selector) {
  return document.querySelector(selector);
}

// DOM 节点统一在这里收口，避免各模块重复 querySelector。
export const elements = {
  providerBadge: query("#provider-badge"),
  candidateName: query("#candidate-name"),
  candidateRole: query("#candidate-role"),
  candidateSummary: query("#candidate-summary"),
  importResumeButton: query("#import-resume-button"),
  resumePackageInput: query("#resume-package-input"),
  candidateYears: query("#candidate-years"),
  templateCount: query("#template-count"),
  sessionMode: query("#session-mode"),
  activeThread: query("#active-thread"),
  templateStatus: query("#template-status"),
  templateSelect: query("#template-select"),
  templateMeta: query("#template-meta"),
  loadTemplateButton: query("#load-template-button"),
  newTemplateButton: query("#new-template-button"),
  copyTemplateButton: query("#copy-template-button"),
  deleteTemplateButton: query("#delete-template-button"),
  templateNameInput: query("#template-name-input"),
  companyNameInput: query("#company-name-input"),
  companyIntroInput: query("#company-intro-input"),
  jobDirectionInput: query("#job-direction-input"),
  jobDescriptionInput: query("#job-description-input"),
  additionalContextInput: query("#additional-context-input"),
  interviewerRoleNameInput: query("#interviewer-role-name-input"),
  roleSelect: query("#role-select"),
  jobSelect: query("#job-select"),
  webSearchInput: query("#web-search-input"),
  saveTemplateButton: query("#save-template-button"),
  startButton: query("#start-button"),
  topicGrid: query("#topic-grid"),
  sessionTitle: query("#session-title"),
  sessionSubtitle: query("#session-subtitle"),
  stageChip: query("#stage-chip"),
  runStatus: query("#run-status"),
  runGraph: query("#run-graph"),
  graphDetail: query("#graph-detail"),
  turnCounter: query("#turn-counter"),
  planList: query("#plan-list"),
  conversation: query("#conversation"),
  answerInput: query("#answer-input"),
  answerButton: query("#answer-button"),
  reportPanel: query("#report-panel"),
  backgroundJobsPanel: query("#background-jobs-panel"),
  observabilityPanel: query("#observability-panel"),
  desktopRuntimePanel: query("#desktop-runtime-panel")
};
