function query(selector) {
  return document.querySelector(selector);
}

function queryAll(selector) {
  return [...document.querySelectorAll(selector)];
}

// Keep DOM lookups centralized so page-shell refactors do not scatter selectors.
export const elements = {
  appShell: query(".app-shell"),
  viewEyebrow: query("#view-eyebrow"),
  viewTitle: query("#view-title"),
  viewDescription: query("#view-description"),
  navButtons: queryAll("[data-nav-view]"),
  viewSections: queryAll("[data-view-section]"),
  overlayRoot: query("#app-overlay"),
  overlayCard: query("#app-overlay-card"),
  overlayEyebrow: query("#app-overlay-eyebrow"),
  overlayTitle: query("#app-overlay-title"),
  overlayDescription: query("#app-overlay-description"),
  overlayTabs: query("#app-overlay-tabs"),
  overlayBody: query("#app-overlay-body"),
  providerBadge: query("#provider-badge"),
  dashboardOverviewPanel: query("#dashboard-overview-panel"),
  dashboardSessionPanel: query("#dashboard-session-panel"),
  startSessionPanel: query("#start-session-panel"),
  settingsOverviewPanel: query("#settings-overview-panel"),
  settingsConfigPanel: query("#settings-config-panel"),
  candidateName: query("#candidate-name"),
  candidateRole: query("#candidate-role"),
  candidateSummary: query("#candidate-summary"),
  importResumeButton: query("#import-resume-button"),
  resumePackageInput: query("#resume-package-input"),
  candidateYears: query("#candidate-years"),
  templateCount: query("#template-count"),
  navSessionMode: query("#nav-session-mode"),
  navActiveThread: query("#nav-active-thread"),
  sessionMode: query("#session-mode"),
  activeThread: query("#active-thread"),
  sessionWorkspaceButtons: queryAll("[data-session-workspace]"),
  sessionWorkspaceSections: queryAll("[data-session-workspace-section]"),
  templateStatus: query("#template-status"),
  templateSearchInput: query("#template-search-input"),
  templateListPanel: query("#template-list-panel"),
  templateLibraryDetailPanel: query("#template-library-detail-panel"),
  templateSelect: query("#template-select"),
  templateMeta: query("#template-meta"),
  templateEditorSummaryPanel: query("#template-editor-summary-panel"),
  loadTemplateButton: query("#load-template-button"),
  newTemplateButton: query("#new-template-button"),
  copyTemplateButton: query("#copy-template-button"),
  deleteTemplateButton: query("#delete-template-button"),
  templateNameInput: query("#template-name-input"),
  companyNameInput: query("#company-name-input"),
  companyIntroInput: query("#company-intro-input"),
  jobDirectionInput: query("#job-direction-input"),
  jobDescriptionInput: query("#job-description-input"),
  additionalContextInput: query("#additional-context-input"),
  interviewerRoleNameInput: query("#interviewer-role-name-input"),
  roleSelect: query("#role-select"),
  jobSelect: query("#job-select"),
  webSearchInput: query("#web-search-input"),
  saveTemplateButton: query("#save-template-button"),
  startButton: query("#start-button"),
  topicGrid: query("#topic-grid"),
  sessionTitle: query("#session-title"),
  sessionSubtitle: query("#session-subtitle"),
  stageChip: query("#stage-chip"),
  runStatus: query("#run-status"),
  runGraph: query("#run-graph"),
  graphDetail: query("#graph-detail"),
  turnCounter: query("#turn-counter"),
  planList: query("#plan-list"),
  conversation: query("#conversation"),
  answerInput: query("#answer-input"),
  answerButton: query("#answer-button"),
  reportPanel: query("#report-panel"),
  backgroundJobsPanel: query("#background-jobs-panel"),
  observabilityPanel: query("#observability-panel"),
  desktopRuntimePanel: query("#desktop-runtime-panel")
};
